import { Service } from '../types/DatabaseModels';

export const mockServices: Service[] = [
  {
    id: 'accounting',
    name: 'Comptabilité',
    code: 'ACC',
    description: 'Service de comptabilité et finances',
    color: '#3b82f6',
    icon: 'calculator',
    canCreateInvoices: true,
    canApproveInvoices: true,
    approvalThreshold: 5000.00,
    requiresManagerApproval: false,
    defaultCurrency: 'EUR',
    paymentTerms: 30,
    costCenter: 'CC001',
    isActive: true,
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-15T14:30:00Z'
  },
  {
    id: 'purchasing',
    name: 'Achats',
    code: 'PUR',
    description: 'Service des achats et approvisionnements',
    color: '#10b981',
    icon: 'shopping-cart',
    canCreateInvoices: true,
    canApproveInvoices: false,
    approvalThreshold: 1000.00,
    requiresManagerApproval: true,
    defaultCurrency: 'EUR',
    paymentTerms: 30,
    costCenter: 'CC002',
    isActive: true,
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-10T11:20:00Z'
  },
  {
    id: 'finance',
    name: 'Finance',
    code: 'FIN',
    description: 'Service financier et trésorerie',
    color: '#f59e0b',
    icon: 'trending-up',
    canCreateInvoices: true,
    canApproveInvoices: true,
    approvalThreshold: 10000.00,
    requiresManagerApproval: false,
    defaultCurrency: 'EUR',
    paymentTerms: 30,
    costCenter: 'CC003',
    isActive: true,
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-20T16:45:00Z'
  },
  {
    id: 'management',
    name: 'Direction',
    code: 'DIR',
    description: 'Direction générale',
    color: '#8b5cf6',
    icon: 'users',
    canCreateInvoices: false,
    canApproveInvoices: true,
    approvalThreshold: 50000.00,
    requiresManagerApproval: false,
    defaultCurrency: 'EUR',
    paymentTerms: 30,
    costCenter: 'CC004',
    isActive: true,
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-05T09:15:00Z'
  },
  {
    id: 'hr',
    name: 'Ressources Humaines',
    code: 'HR',
    description: 'Service des ressources humaines',
    color: '#ec4899',
    icon: 'user-check',
    canCreateInvoices: false,
    canApproveInvoices: false,
    approvalThreshold: 0.00,
    requiresManagerApproval: true,
    defaultCurrency: 'EUR',
    paymentTerms: 30,
    costCenter: 'CC005',
    isActive: true,
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: '2024-01-12T13:30:00Z'
  }
];
