# Generated by Django 5.2.5 on 2025-09-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoice", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocr_text", models.TextField(blank=True, null=True)),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                (
                    "anomaly_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("anomalies_detected", models.JSONField(blank=True, null=True)),
                (
                    "priority_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fraud_risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "ai_model_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("ai_recommendations", models.JSONField(blank=True, null=True)),
                ("suggested_actions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_results",
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
    ]
