# Generated by Django 5.2.5 on 2025-09-16 13:31

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    roles = ['admin', 'manager', 'employee', 'viewer']  # your system roles
    for role in roles:
        Group.objects.get_or_create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=migrations.RunPython.noop),
    ]

