# Generated by Django 5.2.5 on 2025-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_staff_alter_user_id_alter_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "permissions",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                db_table="user_permissions",
                related_name="users",
                to="users.permission",
            ),
        ),
    ]
