# Generated by Django 5.2.5 on 2025-09-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_serviceinsert"),
        ("users", "0002_create_default_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="service_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="departments.service"
            ),
        ),
    ]
