# Generated by Django 5.2.5 on 2025-08-28 12:08

from django.db import migrations

# def add_permissions(apps, schema_editor):
#     Permission = apps.get_model('users', 'Permission')  # Adjust model path
#     permissions = [
#         ('create_invoice', 'Create new invoices'),
#         ('edit_invoice', 'Modify existing invoices'),
#         ('approve_invoice', 'Approve invoices for payment'),
#         ('reject_invoice', 'Reject invoices'),
#         ('transfer_invoice', 'Transfer invoices between departments'),
#         ('delete_invoice', 'Delete invoices (admin only)'),
#         ('view_all_invoices', 'View all invoices in system'),
#         ('manage_users', 'User management (admin only)'),
#         ('view_reports', 'View reports'),
#         ('view_invoices', 'View invoices'),
#         ('view_all_users', 'View all users'),
#         ('view_analytics', 'View analytics'),
#         ('view_notifications', 'View notifications'),
#         ('export_data', 'Export data'),
#     ]

#     for code, description in permissions:
#         Permission.objects.update_or_create(
#             code=code,
#             defaults={'description': description}
#         )
def noop(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_permissions_userpermission"),
    ]
    
    operations = [ 
        migrations.RunPython(noop),
    ]

