# Generated by Django 5.2.5 on 2025-08-28 12:13

from django.db import migrations
from django.utils import timezone

# def addvalues(apps,schema_editor):
#     User = apps.get_model('users', 'User')
#     Permission = apps.get_model('users', 'Permission')
#     UserPermission = apps.get_model('users', 'UserPermission')

#     user = User.objects.get(id='c5f7d859a1de430bb66d9c2211cf51db')
#     admin = User.objects.get(id='cfb47bad128b48c9bf1082b4f298eb9e')

#     permissions = [
#         'create_invoice', 'edit_invoice', 'approve_invoice', 'reject_invoice',
#         'transfer_invoice', 'delete_invoice', 'view_all_invoices', 'manage_users',
#         'view_reports', 'view_invoices', 'view_all_users', 'view_analytics',
#         'view_notifications', 'export_data'
#     ]

#     for code in permissions:
#         perm = Permission.objects.get(code=code)
#         UserPermission.objects.update_or_create(
#             user=user,
#             permission=perm,
#             defaults={'granted_by': admin, 'granted_at': timezone.now()}
#         )

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_insert_permissions_sql"),
    ]

    operations = [        
        migrations.RunPython(noop),
    ]
