# Generated by Django 5.2.5 on 2025-08-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_insert_user_permissions_sql"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="users.UserPermission",
                through_fields=("user", "permission"),
                to="users.permission",
            ),
        ),
    ]
