# Generated by Django 5.2.5 on 2025-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("viewer", "Viewer"),
                    ("approver", "Approver"),
                    ("finance", "Finance"),
                    ("supplier", "Vendor"),
                ],
                max_length=20,
            ),
        ),
    ]
