# Generated by Django 5.2.5 on 2025-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="user",
            name="permissions",
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="granted_by",
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="UserPermission",
        ),
    ]
