# Generated by Django 5.2.5 on 2025-09-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_userpermission_permission_and_more"),
    ]

    operations = []
