# Generated by Django 5.2.5 on 2025-09-02 15:36
#seed group
from django.db import migrations

ROLE_PERMISSIONS = {
    "admin": ["add_user", "change_user", "delete_user", "view_user","view_all_invoices"],
    "manager": ["change_user", "view_user"],
    "staff": ["view_user"],
}

def assign_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for role_name, perm_codenames in ROLE_PERMISSIONS.items():
        try:
            group = Group.objects.get(name=role_name)
        except Group.DoesNotExist:
            print(f"Group not found: {role_name}")
            continue

        for codename in perm_codenames:
            try:
                perm = Permission.objects.get(codename=codename)
                group.permissions.add(perm)
                print(f"Added {codename} to {role_name}")
            except Permission.DoesNotExist:
                print(f"Permission not found: {codename}")

def remove_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for role_name in ROLE_PERMISSIONS.keys():
        try:
            group = Group.objects.get(name=role_name)
            group.permissions.clear()
        except Group.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_seed_roles_and_permissions"),  # The group insertion migration
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(assign_permissions, reverse_code=remove_permissions),
    ]
