# Generated by Django 5.2.5 on 2025-09-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField()),
                ("type", models.CharField(max_length=10)),
                ("object_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("change_message", models.TextField(blank=True)),
                ("notif_type_id", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("inapp", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute", models.TextField(blank=True)),
                (
                    "notif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                    ),
                ),
            ],
        ),
    ]
