# Generated by Django 5.2.5 on 2025-09-16 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications",
                through="notifications.UserNotification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
