# Generated by Django 5.2.5 on 2025-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="type",
            new_name="notiftype",
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
