# Generated by Django 5.2.5 on 2025-09-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_rename_type_notification_notiftype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notif_type_id",
        ),
    ]
