# Generated by Django 5.2.5 on 2025-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="workflow_rules",
            field=models.ManyToManyField(
                related_name="workflow_rules_from_invoice",
                through="invoice.WorkflowRuleServiceLink",
                to="invoice.workflowrule",
            ),
        ),
    ]
