# Generated by Django 5.2.5 on 2025-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("vendor_name", models.CharField(max_length=255)),
                ("vendor_email", models.EmailField(blank=True, max_length=254)),
                ("vendor_phone", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("external_reference", models.CharField(blank=True, max_length=100)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("exchange_rate", models.FloatField(blank=True, null=True)),
                (
                    "base_currency_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("transferred", "Transferred"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_service", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("approval_level", models.IntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("payment_terms", models.IntegerField(default=30)),
                (
                    "late_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("discount_due_date", models.DateField(blank=True, null=True)),
                ("file", models.FileField(upload_to="invoices/")),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_text", models.TextField(blank=True)),
                ("ocr_confidence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("service_transfer", "Service Transfer"),
                            ("assignment_change", "Assignment Change"),
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                            ("comment_added", "Comment Added"),
                            ("file_attached", "File Attached"),
                            ("amount_modified", "Amount Modified"),
                            ("due_date_changed", "Due Date Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("bulk_operation", "Bulk Operation"),
                            ("system_action", "System Action"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("transferred", "Transferred"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("transferred", "Transferred"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("from_service", models.CharField(blank=True, max_length=255)),
                ("to_service", models.CharField(blank=True, max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_rate", models.FloatField(blank=True, null=True)),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cost_center", models.CharField(blank=True, max_length=100)),
                ("gl_account", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("detection_keywords", models.JSONField(blank=True, default=list)),
                ("rois", models.JSONField(blank=True, default=dict)),
                (
                    "sample_image",
                    models.ImageField(blank=True, upload_to="invoice_templates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("time", "Time"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_conditions", models.JSONField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("notify", "Notify"),
                            ("approve", "Approve"),
                            ("escalate", "Escalate"),
                            ("assign", "Assign"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_parameters", models.JSONField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowRuleServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(blank=True, max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("activation_date", models.DateTimeField(blank=True, null=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
    ]
