# Generated by Django 5.2.5 on 2025-09-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_invoices",
                to="invoice.workflowrule",
            ),
        ),
    ]
