# Generated by Django 5.2.5 on 2025-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_invoice_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="FCFA", max_length=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
