# Generated by Django 5.2.5 on 2025-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code (e.g. #FF5733)",
                        max_length=7,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("can_create_invoices", models.BooleanField(default=True)),
                ("can_approve_invoices", models.BooleanField(default=False)),
                (
                    "approval_threshold",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("requires_manager_approval", models.BooleanField(default=False)),
                ("default_currency", models.CharField(default="EUR", max_length=10)),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                ("cost_center", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
