# Generated by Django 5.2.5 on 2025-09-17 15:57

from django.db import migrations

def create_initial_services(apps, schema_editor):
    Service = apps.get_model('departments','Service')
    initial_services = [
        {'code': 'accounting',     'name': 'Accounting'},
        {'code': 'purchasing',     'name': 'Purchasing'},
        {'code': 'finance',        'name': 'Finance'},
        {'code': 'management',     'name': 'Management'},
        {'code': 'hr',             'name': 'Human Resources'},
        {'code': 'administrative', 'name': 'Administrative'},
        {'code': 'computer',       'name': 'IT / Computer'},
        {'code': 'research',       'name': 'Research'},
        {'code': 'quality_control','name': 'Quality Control'},
        {'code': 'logistics',      'name': 'Logistics'},
        {'code': 'maintenance',    'name': 'Maintenance'},
        {'code': 'communications', 'name': 'Communications'},
    ]

    for svc in initial_services:
        Service.objects.update_or_create(
            code=svc['code'],
            defaults={'name': svc['name']}
        )

    #Service.objects.filter(code__in=codes).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_services),
    ]




 